#!/bin/sh
#
# xencommons    Script to start DomD guest
#
# Author:       Andrii Anisov <andrii_anisov@epam.com>
#
# chkconfig: 2345 70 10
# description: Starts and stops xenstored and xenconsoled
### BEGIN INIT INFO
# Provides:          guest_domd
# Required-Start:    $xenstored $xenconsoled
# Should-Start:
# Required-Stop:     $xenstored $xenconsoled
# Should-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop DomD
# Description:       Simple run of DomD, will be updated soon
### END INIT INFO

# not running in Xen dom0 or domU
if ! test -d /proc/xen ; then
	exit 0
fi

do_start () {
    if xl domid DomD &> /dev/null; then
	echo "DomD is already running"
        exit 0
    fi
    xl create /xt/dom.cfg/domd.cfg
}

do_stop () {
    if xl domid DomD &> /dev/null ; then
	echo "DomD is not running"
        exit 0
    fi
    xl destroy DomD
}

do_status () {
    if xl domid DomD &> /dev/null ; then
	echo "DomD is not running"
        exit 0
    else
	xl list DomD
    fi
}

case "$1" in
  start)
	do_start
	;;
  status)
	do_status
	;;
  stop)
	do_stop
	;;
  reload)
	echo >&2 'Reload not available; use force-reload'; exit 1
	;;
  force-reload|restart)
        do_stop
	do_start
	;;
  *)
	# do not advertise unreasonable commands that there is no reason
	# to use with this device
	echo $"Usage: $0 {start|stop|status|restart|force-reload}"
	exit 1
esac

exit $?
