#!/bin/sh
#
# xencommons    Script to start DomA guest
#
# Author:       Andrii Anisov <andrii_anisov@epam.com>
#
# chkconfig: 2345 70 10
# description: Starts and stops xenstored and xenconsoled
### BEGIN INIT INFO
# Provides:          guest_doma
# Required-Start:    $guest_domd
# Should-Start:
# Required-Stop:     $guest_domd
# Should-Stop:
# Default-Start:     2 3 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop DomA
# Description:       Simple run of DomA, will be updated soon
### END INIT INFO

# not running in Xen dom0 or domU
if ! test -d /proc/xen ; then
	exit 0
fi

do_start () {
    echo "Starting DomA"
    if xl domid DomA &> /dev/null; then
	echo "DomA is already running"
        exit 0
    fi

    if pidof -x start_doma.sh > /dev/null ; then
	echo "DomA start is waiting for backends"
	exit 0
    fi

    /xt/scripts/start_doma.sh displbe disks bridge &
    echo "DomA is scheduled to run"
}

do_stop () {
    echo "Stopping DomA"

    killall start_doma.sh &> /dev/null

    if ! xl domid DomA &> /dev/null ; then
	echo "DomA is not running"
        exit 0
    fi
    xl destroy DomA
}

do_status () {
    if ! xl domid DomA &> /dev/null ; then
	echo "DomA is not running"

        if pidof -x start_doma.sh > /dev/null ; then
	    echo "DomA start is waiting for backends"
	fi

        exit 0
    else
	xl list DomA
    fi
}

case "$1" in
  start)
	do_start
	;;
  status)
	do_status
	;;
  stop)
	do_stop
	;;
  reload)
	echo >&2 'Reload not available; use force-reload'; exit 1
	;;
  force-reload|restart)
        do_stop
	do_start
	;;
  *)
	# do not advertise unreasonable commands that there is no reason
	# to use with this device
	echo $"Usage: $0 {start|stop|status|restart|force-reload}"
	exit 1
esac

exit $?
